/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PeerCounsellingRouteImport } from './routes/peer-counselling'
import { Route as ProfessionalCounsellingRouteImport } from './routes/professional-counselling'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PeerCounsellingRoute = PeerCounsellingRouteImport.update({
  id: '/peer-counselling',
  path: '/peer-counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalCounsellingRoute = ProfessionalCounsellingRouteImport.update({
  id: '/professional-counselling',
  path: '/professional-counselling',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/peer-counselling': typeof PeerCounsellingRoute
  '/professional-counselling': typeof ProfessionalCounsellingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/peer-counselling': typeof PeerCounsellingRoute
  '/professional-counselling': typeof ProfessionalCounsellingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/peer-counselling': typeof PeerCounsellingRoute
  '/professional-counselling': typeof ProfessionalCounsellingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/peer-counselling' | '/professional-counselling'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/peer-counselling' | '/professional-counselling'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/peer-counselling'
    | '/professional-counselling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PeerCounsellingRoute: typeof PeerCounsellingRoute
  ProfessionalCounsellingRoute: typeof ProfessionalCounsellingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peer-counselling': {
      id: '/peer-counselling'
      path: '/peer-counselling'
      fullPath: '/peer-counselling'
      preLoaderRoute: typeof PeerCounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-counselling': {
      id: '/professional-counselling'
      path: '/professional-counselling'
      fullPath: '/professional-counselling'
      preLoaderRoute: typeof ProfessionalCounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PeerCounsellingRoute: PeerCounsellingRoute,
  ProfessionalCounsellingRoute: ProfessionalCounsellingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
