REVOKE EXECUTE ON FUNCTION public.alert_admins_new_payment() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.alert_admins_new_donation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.alert_admins_new_account() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.touch_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_appointment_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_slot_booking() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_my_counsellor_record(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_my_counsellor_record(uuid) TO authenticated, service_role;